# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tutorial_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.TutorialSeries'),
        ),
    ]
